```{r, message = FALSE, warning=FALSE}
# Install packages to make sankey diagrams
install.packages("Rtools")
install.packages("cli")
install.packages("devtools")
devtools::install_github("davidsjoberg/ggsankey")
library(ggsankey)

# Install other libraries
library(tidyverse)
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(grid)
library(gridExtra)
library(ggpubr)
```

```{r, message = FALSE, results='hide'}
# Read data as csv
gas_waves_data <- read.csv("Waves_GasPayment.csv")

gas_waves_data$x1 <- as.character(gas_waves_data$x1)
gas_waves_data$x2 <- as.character(gas_waves_data$x2)
gas_waves_data$x3 <- as.character(gas_waves_data$x3)

data_long <- gas_waves_data %>% # Convert data into long format using the ggsankey format
  make_long(x1, x2, x3) # See guidance on make_long() function on github
```

```{r, message = FALSE, results='hide'}
# Set labels
x_labels <- c('Wave 1', 'Wave 2', 'Wave 3')

# Read data as csv
GasPayment_Freq <- data_long %>%
  mutate(node = fct_relevel(node, "No data", "0", "1", "2", "3", "4", 
                            "5", "6", "8", "10"),
         next_node = fct_relevel(next_node, "No data", "0", "1", "2", "3", "4", 
                                 "5", "6", "8", "10"))%>%
  ggplot(aes(x = x, next_x = next_x, # x, next_x, node and next_node are specified by make_long function above
          node = node, next_node = next_node,
          fill = factor(node),
          label = node))+
  geom_sankey(flow.alpha =.8, # Set transparency levels on flows
              node.color = 1,
              show.legend = FALSE)+ 
  geom_sankey_label(color = 1, # Set labels
                    show.legend = FALSE,
                    size=6)+
  scale_fill_manual(values = c("0" = "#8e0152",
                               "1" = "#c51b7d", 
                               "2" = "#de77ae", 
                               "3" = "#f1b6da", 
                               "4" = "#fde0ef", 
                               "5" = "#f7f7f7", 
                               "6" = "#e6f5d0", 
                               "7" = "#b8e186", 
                               "8" = "#7fbc41", 
                               "9" = "#4d9221",
                               "10" = "#276419",
                               "NA" = "D3D3D3"))+
  theme_sankey(base_size = 20)+
  xlab("")+
  scale_x_discrete(labels = x_labels) # Set labels from x_labels object above
```

```{r, message = FALSE, results='hide'}
tiff('gaspayment_freq_500.tiff', units = "in", res = 500, height = 13, width = 17)
plot(GasPayment_Freq)
dev.off()
```

```{r, message = FALSE, results='hide'}
# Read data as csv
elec_waves_data <- read.csv("Waves_ElectricityPayment.csv")

elec_waves_data$x1 <- as.character(elec_waves_data$x1)
elec_waves_data$x2 <- as.character(elec_waves_data$x2)
elec_waves_data$x3 <- as.character(elec_waves_data$x3)

data_long <- elec_waves_data %>% # Convert data into long format using the ggsankey format
  make_long(x1, x2, x3) # See guidance on make_long() function on github
```

```{r, message = FALSE, results='hide'}
# Set labels
x_labels <- c('Wave 1', 'Wave 2', 'Wave 3')

# Read data as csv
ElecPayment_Freq <- data_long %>%
  mutate(node = fct_relevel(node, "No data", "0", "1", "2", "3", "4", 
                            "5", "6", "8", "10"),
         next_node = fct_relevel(next_node, "No data", "0", "1", "2", "3", "4", 
                                 "5", "6", "8", "10"))%>%
  ggplot(aes(x = x, next_x = next_x, # x, next_x, node and next_node are specified by make_long function above
          node = node, next_node = next_node,
          fill = factor(node),
          label = node))+
  geom_sankey(flow.alpha =.8, # Set transparency levels on flows
              node.color = 1,
              show.legend = FALSE)+ 
  geom_sankey_label(color = 1, # Set labels
                    show.legend = FALSE,
                    size=6)+
  scale_fill_manual(values = c("0" = "#8e0152",
                               "1" = "#c51b7d", 
                               "2" = "#de77ae", 
                               "3" = "#f1b6da", 
                               "4" = "#fde0ef", 
                               "5" = "#f7f7f7", 
                               "6" = "#e6f5d0", 
                               "7" = "#b8e186", 
                               "8" = "#7fbc41", 
                               "9" = "#4d9221",
                               "10" = "#276419",
                               "NA" = "D3D3D3"))+
  theme_sankey(base_size = 20)+
  xlab("")+
  scale_x_discrete(labels = x_labels) # Set labels from x_labels object above
```

```{r, message = FALSE, results='hide'}
tiff('electricitypayment_freq_500.tiff', units = "in", res = 500, height = 13, width = 17)
plot(ElecPayment_Freq)
dev.off()
```

```{r, message = FALSE, results='hide'}
install.packagesinstall.packages("GGally")
library(GGally)
install.packages("viridis")
library(viridis)

totalbill_fueltype_elec <- read.csv("TotalBill_FuelType_Elec.csv")

totalbill_fueltype_elec$Fuel.type <- factor(totalbill_fueltype_elec$Fuel.type,
                       labels = c("Electricity",
                       "Total"))

tiff('parcoord_billelec_400.tiff', units = "in", res = 400, height = 7, width = 10)
ggparcoord(data = totalbill_fueltype_elec,
           columns = 1:3,
           scale = "globalminmax",
           groupColumn = "Fuel.type",
           showPoints = TRUE)+
  scale_colour_manual(values = c(
                      "Electricity" = "maroon2",
                      "Total" = "grey"))+
  theme_minimal()+ 
  theme(legend.position = "none")+
  ylim(0, 650)
dev.off()

totalbill_fueltype_gas <- read.csv("TotalBill_FuelType_Gas.csv")

totalbill_fueltype_gas$Fuel.type <- factor(totalbill_fueltype_gas$Fuel.type,
                       labels = c("Gas",
                       "Total"))

tiff('parcoord_billgas_400.tiff', units = "in", res = 400, height = 7, width = 10)
ggparcoord(data = totalbill_fueltype_gas,
           columns = 1:3,
           scale = "globalminmax",
           groupColumn = "Fuel.type",
           showPoints = TRUE)+
  scale_colour_manual(values = c(
                      "Gas" = "maroon2",
                      "Total" = "grey"))+
  theme_minimal()+ 
  theme(legend.position = "none")+
  ylim(0, 650)
dev.off()
```
